# Generated by Django 5.0.1 on 2024-01-16 17:33

import django.core.validators
import src.base.services
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_lib", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.base.services.get_path_upload_cover_track,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg"]
                    ),
                    src.base.services.validate_size_image,
                ],
            ),
        ),
    ]
